version: "3"

services:
  node-server:
    container_name: node-server
    build: ./node-server
    image: node-server
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./node-server:/node-server
      - /node-server/node_modules
    command: nodemon -L --inspect=0.0.0.0 ./bin/www
    links:
      - mongodb

  mongodb:
    container_name: mongo
    image: mongo
    stdin_open: true
    tty: true
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  nginx:
    container_name: nginx-server
    restart: always
    build:
      context: ./nginx
    ports:
      - "8080:80"
        